//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Entity_Proje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class firatuca_Db_Cv_EntityEntities : DbContext
    {
        public firatuca_Db_Cv_EntityEntities()
            : base("name=firatuca_Db_Cv_EntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Deneyim> Tbl_Deneyim { get; set; }
        public virtual DbSet<Tbl_Hakkimda> Tbl_Hakkimda { get; set; }
        public virtual DbSet<Tbl_İletisim> Tbl_İletisim { get; set; }
        public virtual DbSet<Tbl_Yetenek> Tbl_Yetenek { get; set; }
    }
}
