//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Entity_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Deneyim
    {
        public int Id { get; set; }
        public string FirmaAd { get; set; }
        public string Pozisyon { get; set; }
        public string Süre { get; set; }
        public string Açıklama { get; set; }
    }
}
